from __future__ import annotations

from typing import Dict, List, Optional

IGNORED_BRAND_KEYWORDS = {
    "onitsuka",
    "onitsuka tiger",
    "鬼塚虎",
    "鬼冢虎",
    "品牌",
    "品牌名",
}

SHOE_QUERY_ALIASES: Dict[str, List[str]] = {
    "MEXICO 66": ["经典款", "复古", "墨西哥66", "经典"],
    "MEXICO 66 NM": [],
    "MEXICO 66 SD": [],
    "MEXICO 66 SLIP-ON": ["无绑带经典", "经典一脚蹬", "一脚蹬"],
    "MEXICO 66 PARATY": ["paraty"],
    "MEXICO 66 TGRS": ["tgrs", "芭蕾风", "芭蕾", "芭蕾鞋"],
    "SLIP-ON": ["无绑带", "无鞋带", "没鞋带", "不系带", "不用系鞋带"],
    "TOKUTEN": ["德训", "德训风格"],
    "SERRANO": ["赛车", "赛车风", "薄底", "赛车鞋"],
    "GSM": ["平板鞋", "平底鞋"],
    "EDR 78": [],
    "DELECITY": ["delecity l"],
    "LAWNSHIP": [],
    "ULTIMATE 81": [],
    "TIGER CORSAIR": ["corsair"],
    "BIG LOGO TRAINER": ["big logo"],
    "TIGRUN": [],
    "TIGTRAIL": [],
    "TRASPIKE": [],
    "DENTIGRE": [],
    "DELEGATION": [],
    "ADMIX TRAINER": ["admix"],
    "MOAL 77": [],
    "COLORADO EIGHTY-FIVE": [],
    "COLESNE": [],
    "OHBORI": [],
    "REBILAC": [],
    "TSUNAHIKI": [],
    "TIGER MOC": [],
    "TIGER RODEANO": [],
    "WINTER HEAVEN": [],
    "SIDE GORE BOOT": ["side gore"],
    "LACE-UP": ["系带"],
    "BLUCHER": [],
    "TIGER LOAFER": ["loafer"],
}

BRAND_QUERY_ALIASES: Dict[str, List[str]] = {
    "印花": ["印花款", "有印花", "印着图案", "花印", "printed", "print"],
    "图案": ["有图案", "花纹", "图形", "图样", "pattern"],
    "刺绣": ["绣花", "绣标", "绣线", "embroidered", "embroidery"],
    "贴布绣": ["贴布", "布贴", "贴章", "patch", "applique"],
    "水洗": ["水洗感", "做旧", "做旧感", "旧旧的", "vintage wash", "washed"],
    "扎染": ["晕染", "渐染", "tie dye", "tie-dye"],
    "牛仔": ["丹宁", "denim", "牛仔布"],
    "针织": ["毛织", "knit", "knitted"],
    "皮质": ["皮革", "皮面", "皮的", "皮感", "leather"],
    "条纹": ["横条", "竖条", "条纹感", "stripe", "striped"],
    "格纹": ["格子", "格纹图案", "check", "checked", "plaid"],
    "花卉": ["花朵", "花花", "floral", "flower"],
    "涂鸦": ["手绘感", "graffiti"],
    "拼接": ["撞色拼接", "多材质", "拼色", "patchwork"],
    "撞色": ["对比色", "拼色", "撞色设计", "contrast"],
    "铆钉": ["钉珠", "金属钉", "stud", "studded"],
    "亮片": ["闪片", "亮闪", "bling", "sequins"],
    "漆皮": ["亮皮", "亮面皮", "patent"],
    "蕾丝": ["镂空花边", "lace", "透气", "花边"],
    "经典": ["经典款", "常青款", "基础经典", "不过时"],
    "纯色": [
        "一个颜色",
        "统一颜色",
        "纯色调",
        "单色",
        "净色",
        "没有图案",
        "solid color",
    ],
    "简约": [
        "简单",
        "简单的",
        "不花哨",
        "干净",
        "干净利落",
        "基础款",
        "minimal",
        "minimalist",
    ],
    "复古": ["怀旧", "老派", "vintage", "retro"],
    "法式": ["法式感", "法风", "french"],
    "度假": ["假日", "海边", "旅行感", "resort", "vacation"],
    "飞行员": ["飞行", "飞行夹克", "bomber", "pilot"],
    "工装": ["机能", "utility", "workwear"],
    "优雅": ["气质", "温柔", "elegant"],
    "个性": ["特别", "有设计感", "设计感", "不普通"],
    "休闲": ["日常", "好搭", "随性", "casual"],
    "时尚": ["潮流", "潮", "fashion"],
    "宽松": ["oversize", "廓形", "松身", "大版型", "宽版"],
    "修身": ["贴身", "显身材", "收身", "slim"],
    "阔腿": ["宽腿", "wide leg", "wide-leg"],
    "直筒": ["直筒版型", "straight"],
    "短袖": ["短袖款", "短袖的", "short sleeve"],
    "长袖": ["长袖款", "long sleeve"],
    "无袖": ["无袖款", "sleeveless"],
    "连帽": ["带帽", "帽衫", "hooded"],
    "套头": ["pullover"],
    "拉链": ["拉链款", "zip", "zip-up"],
    "开衫": ["cardigan"],
    "圆领": ["crew neck", "crewneck"],
    "吊带": ["细肩带", "camisole", "cami"],
    "双排扣": ["double breasted", "double-breasted"],
    "防风": ["挡风", "windbreaker", "wind proof"],
    "铺棉": ["棉服感", "夹棉", "padded"],
    "厚底": [
        "增高",
        "显高",
        "底高",
        "厚底的",
        "厚底款",
        "高底",
        "platform",
        "chunky sole",
    ],
}

GENDER_FILTER_IDS: Dict[str, str] = {
    "女性": "19268",
    "女子": "19162",
    "男性": "19294",
    "男子": "19161",
    "中性": "19160",
    "儿童": "19163",
}

PRICE_FILTER_VALUES = {
    "850-1150",
    "1150-1450",
    "1450-1750",
    "2050-2350",
    "3850-4150",
}

SIZE_FILTER_IDS: Dict[str, str] = {
    "20.5": "19178",
    "21.5": "19179",
    "19.5": "5742",
    "21": "5744",
    "22.5": "5746",
    "23.5": "5748",
    "25": "5750",
    "26": "5751",
    "27": "5741",
    "28.5": "5743",
    "30": "5745",
    "31.5": "5747",
    "32.5": "5749",
    "33": "5764",
    "33.5": "5752",
    "34.5": "5765",
    "35": "5753",
    "35.5": "5839",
    "36": "5631",
    "37": "5439",
    "37.5": "5639",
    "38": "5440",
    "39": "5441",
    "39.0": "19124",
    "39.5": "5650",
    "40": "5442",
    "40.0": "19125",
    "40.5": "5660",
    "41.5": "5665",
    "42": "5670",
    "42.5": "5674",
    "43.5": "5680",
    "44": "5685",
    "44.0": "19126",
    "44.5": "5690",
    "45": "5696",
    "45.0": "19127",
    "46": "5702",
    "46.5": "5707",
    "47": "5713",
    "48": "5719",
    "110": "5604",
    "120": "5608",
    "130": "5609",
    "140": "5799",
    "XS": "5494",
    "S": "5510",
    "M": "5523",
    "L": "5533",
    "XL": "5543",
    "2XL": "5550",
}


def normalize_sort(value: Optional[str], *, default: str = "") -> str:
    candidate = str(value or default or "").strip()
    return (
        candidate
        if candidate in {"", "new", "sales", "price:asc", "price:desc"}
        else default
    )


def build_where_payload(
    *,
    gender: Optional[str] = None,
    size: Optional[str] = None,
    color: Optional[str] = None,
    price_range: Optional[str] = None,
) -> Dict[str, str]:
    payload = {
        "gender": str(gender or "").strip(),
        "size": str(size or "").strip(),
        "color": str(color or "").strip(),
        "price": str(price_range or "").strip(),
    }
    return {key: value for key, value in payload.items() if value}
